import { CheckCircle2, XCircle, Info } from "lucide-react";
import type { MetadataQuality } from "@/types/sbom";

export function MetadataQualityCard({ quality }: { quality: MetadataQuality }) {
  const metadataChecks = [
    { key: 'purl', label: 'Package URLs (PURLs)', description: 'Universal identifiers for components', guidance: 'Populated by Syft, Trivy, and cdxgen when scanning package managers (npm, Maven, etc.).', weight: 20 },
    { key: 'licenses', label: 'License Metadata', description: 'Legal compliance and usage rights', guidance: 'Extracted securely by Trivy, Syft, and FOSSA. SPDX IDs are standard.', weight: 20 },
    { key: 'hashes', label: 'Cryptographic Hashes', description: 'Ensures file integrity and safety', guidance: 'Generated by tools like Syft. For cdxgen, it depends heavily on the ecosystem (e.g., existing in lockfiles) or deeper analysis flags.', weight: 15 },
    { key: 'supplier', label: 'Supplier/Author Info', description: 'Origin and maintenance tracking', guidance: 'Depends on package registry metadata. Some scanners require explicit fetching flags (e.g. FETCH_LICENSE=true in cdxgen) or manual enrichment.', weight: 15 },
    { key: 'properties', label: 'Extended Properties', description: 'Tool-specific enriched metadata', guidance: 'Custom extensions (key/value). Often used by Trivy or cdxgen for configuration flags.', weight: 10 },
    { key: 'tools', label: 'Creator Tools', description: 'Tracks the tool that generated this SBOM', guidance: 'Standard in CycloneDX. Tools like Syft, Trivy, and cdxgen inject themselves into the metadata.tools node.', weight: 10 },
    { key: 'dependencies', label: 'Dependency Graph', description: 'Relationship links between components', guidance: 'Essential for tree visualization. Supported strongly by cdxgen and Syft.', weight: 10 },
  ];

  return (
    <div className="space-y-6">
      <div className="space-y-3">
        {metadataChecks.map((check) => {
          const isPassed = quality.checks[check.key as keyof typeof quality.checks];
          return (
            <div key={check.key} className="flex gap-4 p-3 rounded-lg border bg-background/50 relative overflow-hidden group">
              <div className={`flex-none mt-1 ${isPassed ? 'text-green-500' : 'text-slate-300'}`}>
                {isPassed ? <CheckCircle2 className="h-5 w-5" /> : <XCircle className="h-5 w-5" />}
              </div>
              <div className="space-y-1 relative z-10 w-full pr-2">
                <div className="flex items-center gap-2">
                  <h5 className="font-semibold text-sm">{check.label}</h5>
                  <span className="text-[10px] text-muted-foreground px-1.5 py-0.5 border rounded-full">
                    {check.weight} pts
                  </span>
                </div>
                <p className="text-xs text-muted-foreground">{check.description}</p>
                
                <div className="flex items-start gap-1.5 mt-2 bg-blue-50/50 p-2 rounded text-xs text-blue-800/80 dark:bg-blue-900/10 dark:text-blue-300">
                  <Info className="h-3.5 w-3.5 mt-0.5 flex-none" />
                  <span>{check.guidance}</span>
                </div>
              </div>
              <div 
                className={`absolute left-0 top-0 bottom-0 w-1 transition-all group-hover:w-1.5 ${
                  isPassed ? 'bg-green-500' : 'bg-slate-200'
                }`} 
              />
            </div>
          );
        })}
      </div>

      <div className="p-4 rounded-lg bg-blue-50 border border-blue-100 flex gap-3 text-blue-800">
        <Info className="h-5 w-5 flex-none" />
        <div className="text-xs space-y-1">
          <p className="font-bold">How is this scored?</p>
          <p className="opacity-80">
            A category is marked as "complete" if over 50% of the components in this SBOM contain that specific metadata field. Scores above 90 earn an A grade.
          </p>
        </div>
      </div>
    </div>
  );
}
